openapi: '3.0.2'
info:
  title: Shared-Wallet-App API
  description: 共有家計簿アプリのAPI仕様
  version: '1.0'
servers:
  - url: http://localhost:3001
    description: 開発環境
  - url: https://api.example.com
    description: 本番環境
paths:
  /v1/payment/registration:
    post:
      summary: Inputページから入力されたデータを登録するAPI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paymentDate:
                  type: string
                  format: date
                  description: 収支日
                paymentType:
                  type: boolean
                  description: 収支種別
                totalAmount:
                  type: number
                  description: 合計金額
                categoryID:
                  type: number
                  description: カテゴリーID
                memo:
                  type: string
                  description: メモ（大）
                memos:
                  type: array
                  items:
                    type: object
                    properties:
                      memo:
                        type: string
                        description: メモ
                      amount:
                        type: number
                        description: 金額
                  description: メモ（小）
      responses:
        '201':
          description: OK
        '500':
          description: Internal Server Error
  /daily-summary:
    get:
      summary: 月の各日の支出と収入の合計を取得する
      parameters:
        - name: month
          in: query
          description: 対象の月（1から12の数字）
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 12
        - name: year
          in: query
          description: 対象の年
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 成功
          content:
            application/json:
              example:
                dailySummary:
                  - date: '2023-11-01'
                    spendingTotal: 1000
                    incomeTotal: 500
                  - date: '2023-11-02'
                    spendingTotal: 1000
                    incomeTotal: 500
                  # ... 1月分の日付ごとのデータ
        '400':
          description: バリデーションエラー
          content:
            application/json:
              example:
                message: バリデーションエラーが発生しました。
                details:
                  - field: month
                    message: '月は1から12の数字で指定してください。'
                  - field: year
                    message: '年は有効な数字で指定してください。'
