openapi: '3.0.2'
info:
  title: Shared-Wallet-App API
  description: 共有家計簿アプリのAPI仕様
  version: '1.0'
servers:
  - url: http://localhost:3001
    description: 開発環境
  - url: https://api.example.com
    description: 本番環境
paths:
  /registration:
    put:
      summary: Inputページから入力されたデータを登録するAPI
      tags:
        - '/v1/payment'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paymentDate:
                  type: string
                  format: date
                  description: 収支日
                paymentType:
                  type: boolean
                  description: 収支種別
                totalAmount:
                  type: number
                  description: 合計金額
                categoryID:
                  type: number
                  description: カテゴリーID
                memo:
                  type: string
                  description: メモ（大）
                memos:
                  type: array
                  items:
                    type: object
                    properties:
                      memo:
                        type: string
                        description: メモ
                      amount:
                        type: number
                        description: 金額
                  description: メモ（小）
      responses:
        '201':
          description: Created
        '500':
          description: Internal Server Error
  /get_all:
    get:
      summary: 現在の総資産を取得するAPI
      tags:
        - '/v1/payment'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalAssets:
                    type: number
        '500':
          description: Internal Server Error
