openapi: '3.0.2'
info:
  title: Shared-Wallet-App API
  description: 共有家計簿アプリのAPI仕様
  version: '1.0'
servers:
  - url: http://localhost:3001
    description: 開発環境
  - url: https://api.example.com
    description: 本番環境
paths:
  /put:
    post:
      summary: Inputページから入力されたデータを登録するAPI
      tags:
        - '/v1/payment'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paymentDate:
                  type: string
                  format: date
                  example: 2024-01-01
                  description: 収支日
                paymentType:
                  type: boolean
                  example: true
                  description: 収支種別
                totalAmount:
                  type: number
                  example: 500
                  description: 合計金額
                categoryID:
                  type: number
                  example: 1
                  description: カテゴリーID
                memo:
                  type: string
                  example: マクドナルド
                  description: メモ（大）
                memos:
                  type: array
                  items:
                    type: object
                    properties:
                      memo:
                        type: string
                        example: ハンバーガー
                        description: メモ
                      amount:
                        type: number
                        example: 500
                        description: 金額
                  description: メモ（小）
      responses:
        '201':
          description: Created
        '500':
          description: Internal Server Error
  /get/all:
    post:
      summary: 現在の総資産・月間収支を取得するAPI
      tags:
        - '/v1/payment'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                yearMonth:
                  type: string
                  format: date
                  example: 2024-01
                  description: 取得年月
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  totalAssets:
                    type: number
                    example: 50000
                    description: 現在総資産
                  monthlyBalance:
                    type: array
                    items:
                      type: object
                      properties:
                        yearMonth:
                          type: string
                          format: date
                          example: 2024-01
                          description: 年月
                        monthSpending:
                          type: number
                          example: 500
                          description: 月間支出
                        monthIncome:
                          type: number
                          example: 30000
                          description: 月間収入
                    description: 月間収支
        '500':
          description: Internal Server Error
  /get/detail:
    post:
      summary: 月ごとの収支データを取得するAPI
      tags:
        - '/v1/payment'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                yearMonth:
                  type: string
                  format: date
                  example: 2024-01
                  description: 取得年月
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    yearMonth:
                      type: string
                      format: date
                      example: 2024-01
                      description: 取得年月
                    monthlyPayments:
                      type: array
                      items:
                        type: object
                        properties:
                          seqId:
                            type: number
                            example: 1
                            description: シーケンスID
                          paymentDate:
                            type: string
                            format: date
                            example: 2024-01-01
                            description: 収支日
                          paymentType:
                            type: boolean
                            example: true
                            description: 収支種別
                          totalAmount:
                            type: number
                            example: 500
                            description: 合計金額
                          categoryID:
                            type: number
                            example: 1
                            description: カテゴリーID
                          memo:
                            type: string
                            example: マクドナルド
                            description: メモ（大）
                          memos:
                            type: array
                            items:
                              type: object
                              properties:
                                memo:
                                  type: string
                                  example: ハンバーガー
                                  description: メモ
                                amount:
                                  type: number
                                  example: 500
                                  description: 金額
                            description: メモ（小）
        '500':
          description: Internal Server Error
